<#
.SYNOPSIS
    Creates the updater signing keypair, writes its public half into
    webapp/src-tauri/tauri.conf.json, and records the private half in a
    gitignored updater.properties.

.DESCRIPTION
    Run this once. The keypair is the identity the desktop auto-updater trusts:
    an installed app only accepts an update whose signature matches the public
    key baked into the build it is running. Losing the private key is not fatal
    the way the Android keystore is -- generate a new pair, ship it in the next
    build -- but every already-installed copy stops taking updates until it is
    manually reinstalled onto the new key. Back up the .key file and its
    password somewhere durable.

    The two halves have to move together, which is the whole reason this is a
    script rather than a list of steps. A private key in CI that does not match
    the public key in the build produces a release that looks perfect and that
    every installed app silently rejects. Generating the pair and rewriting the
    config in one action makes them impossible to skew by hand;
    release-desktop.yml re-checks the pairing before it builds.

    Nothing this script writes is committed. Both key files and
    webapp/updater.properties are gitignored.

.PARAMETER Force
    Overwrite an existing key. Refused by default, because replacing the key
    stops updates for anyone already running a build signed with the old one.

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\New-UpdaterKey.ps1

.EXAMPLE
    cd webapp; npm run desktop:updater:key
#>
[CmdletBinding()]
param(
    [string]$KeyPath,
    [string]$PropertiesPath,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# scripts/ sits at the repository root, but the Tauri project is under webapp/.
$repoRoot = Split-Path -Parent $PSScriptRoot
$webappDir = Join-Path $repoRoot 'webapp'
$configPath = Join-Path $webappDir 'src-tauri\tauri.conf.json'
if (-not $KeyPath) { $KeyPath = Join-Path $webappDir 'klikklak-updater.key' }
if (-not $PropertiesPath) { $PropertiesPath = Join-Path $webappDir 'updater.properties' }

if ((Test-Path $KeyPath) -and -not $Force) {
    throw "Updater key already exists at $KeyPath. Re-run with -Force only if you are certain no installed app is running a build signed with it."
}

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    throw 'Node is required and was not found on PATH. See docs/desktop-release.md.'
}

# The Tauri CLI ships in webapp's dev dependencies, so npm ci has to have run.
# Calling its JS entry directly keeps this off `npx`, which would otherwise go
# to the network when the local copy is missing rather than saying so.
$cli = Join-Path $webappDir 'node_modules\@tauri-apps\cli\tauri.js'
if (-not (Test-Path $cli)) {
    throw 'The Tauri CLI is not installed. Run "npm ci" in webapp first.'
}

# A generated 32-character password beats a memorable one here: it is written
# straight to the gitignored properties file and to a GitHub secret, and is
# never typed by hand.
$bytes = [byte[]]::new(24)
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$password = [Convert]::ToBase64String($bytes) -replace '[+/=]', 'x'

$generate = @($cli, 'signer', 'generate', '--ci', '-p', $password, '-w', $KeyPath)
if ($Force) { $generate += '-f' }
& node @generate
if ($LASTEXITCODE -ne 0) { throw "tauri signer generate failed with exit code $LASTEXITCODE." }

$publicKeyPath = "$KeyPath.pub"
if (-not (Test-Path $publicKeyPath)) { throw "Expected a public key at $publicKeyPath." }
$publicKey = (Get-Content $publicKeyPath -Raw).Trim()

# Rewrite only plugins.updater.pubkey. Round-tripping through the JSON parser
# would reformat the whole file and lose nothing but the diff's readability, so
# the value is replaced in place, in the two-space style the file is written in.
# The instance Replace is what takes a count; the static one would read a 1 as
# RegexOptions and quietly rewrite every match.
$config = Get-Content $configPath -Raw
$regex = [regex]'(?m)^(?<indent>\s*)"pubkey":\s*"[^"]*"'
if (-not $regex.IsMatch($config)) { throw "No plugins.updater.pubkey field in $configPath." }
# A minisign public key is base64, so it carries no '$' for the replacement
# pattern to read as a group reference.
$config = $regex.Replace($config, '${indent}"pubkey": "' + $publicKey + '"', 1)
# Not Set-Content -Encoding UTF8: on Windows PowerShell that writes a BOM, and a
# BOM in tauri.conf.json fails the bundler's JSON parse.
[System.IO.File]::WriteAllText($configPath, $config, (New-Object System.Text.UTF8Encoding $false))

@(
    '# Generated by scripts/New-UpdaterKey.ps1. Gitignored - never commit.',
    "keyFile=$([System.IO.Path]::GetFullPath($KeyPath) -replace '\\', '/')",
    "keyPassword=$password"
) | Set-Content -Path $PropertiesPath -Encoding ASCII

# A key inside the repository but outside the ignored paths would be committed
# on the next `git add -A`. Warn rather than fail, since the caller may have
# their own arrangement.
$fullKeyPath = [System.IO.Path]::GetFullPath($KeyPath)
if ($fullKeyPath.StartsWith($repoRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    & git -C $repoRoot check-ignore -q -- $fullKeyPath 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "$fullKeyPath is inside the repository but is NOT gitignored. Move it out or add it to .gitignore before committing anything."
    }
}

Write-Host ''
Write-Host 'Updater keypair created.' -ForegroundColor Green
Write-Host "  private key : $KeyPath"
Write-Host "  public key  : $publicKeyPath"
Write-Host "  properties  : $PropertiesPath"
Write-Host "  pubkey written into src-tauri/tauri.conf.json"
Write-Host ''
Write-Host 'Back up the private key and its password now, and commit the changed' -ForegroundColor Yellow
Write-Host 'tauri.conf.json -- the public key has to ship in the build that will' -ForegroundColor Yellow
Write-Host 'verify updates signed with the private one.' -ForegroundColor Yellow
Write-Host ''
Write-Host 'To let CI sign releases, publish the same material as secrets:' -ForegroundColor Cyan
Write-Host '  cd webapp; npm run desktop:updater:secrets'
