<#
.SYNOPSIS
    Creates the release signing keystore and the gitignored keystore.properties
    that webapp/android/app/build.gradle reads.

.DESCRIPTION
    Run this once. The keystore it produces is the permanent identity of the
    app: Android will only install an update over an existing install when both
    are signed by the same key. If you lose it, every phone running the app must
    uninstall before it can take another build. Back up both the .jks and its
    password somewhere durable -- a password manager, not this repository.

    Nothing this script writes is committed. webapp/android/app/*.jks is covered
    by the repository-wide *.jks rule and webapp/android/keystore.properties is
    ignored by name.

.PARAMETER Force
    Overwrite an existing keystore. Refused by default, because replacing the
    key silently breaks updates for anyone who already installed the app.

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\New-ReleaseKeystore.ps1

.EXAMPLE
    cd webapp; npm run android:keystore:create
#>
[CmdletBinding()]
param(
    [string]$KeystorePath,
    [string]$PropertiesPath,
    [string]$Alias = 'qtr-pairing-release',
    [int]$ValidityDays = 10000,
    [string]$DistinguishedName = 'CN=QTR Pairing, O=QTR-Games, C=US',
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# scripts/ sits at the repository root, but the Capacitor project is one level
# down in webapp/. Every path below has to account for that offset.
$repoRoot = Split-Path -Parent $PSScriptRoot
$androidDir = Join-Path $repoRoot 'webapp\android'
if (-not $KeystorePath) { $KeystorePath = Join-Path $androidDir 'app\qtr-release.jks' }
if (-not $PropertiesPath) { $PropertiesPath = Join-Path $androidDir 'keystore.properties' }

if ((Test-Path $KeystorePath) -and -not $Force) {
    throw "Keystore already exists at $KeystorePath. Re-run with -Force only if you are certain no phone has installed a build signed with it."
}

$keytool = $null
foreach ($candidate in @($env:JAVA_HOME, 'C:\Program Files\Eclipse Adoptium\jdk-21', 'C:\Program Files\Java\jdk-21')) {
    if ($candidate) {
        $probe = Join-Path $candidate 'bin\keytool.exe'
        if (Test-Path $probe) { $keytool = $probe; break }
    }
}
if (-not $keytool) {
    $command = Get-Command keytool -ErrorAction SilentlyContinue
    if ($command) { $keytool = $command.Source }
}
if (-not $keytool) { throw 'keytool not found. Install Temurin JDK 21 or set JAVA_HOME. See docs/android-build.md.' }

# A generated 32-character password beats a memorable one here: it is written
# straight to the gitignored properties file and to a GitHub secret, and is
# never typed by hand.
$bytes = [byte[]]::new(24)
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$password = [Convert]::ToBase64String($bytes) -replace '[+/=]', 'x'

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $KeystorePath) | Out-Null
if ((Test-Path $KeystorePath) -and $Force) { Remove-Item $KeystorePath -Force }

& $keytool -genkeypair -v `
    -keystore $KeystorePath `
    -storepass $password -keypass $password `
    -alias $Alias `
    -keyalg RSA -keysize 4096 -validity $ValidityDays `
    -dname $DistinguishedName
if ($LASTEXITCODE -ne 0) { throw "keytool failed with exit code $LASTEXITCODE." }

# storeFile is written relative to webapp/android/ when the keystore lives
# inside it, so the properties file stays portable and free of absolute
# developer paths. A keystore deliberately kept outside the repo is recorded
# absolutely instead. Either way the separator is normalised to '/', because a
# .properties file treats a backslash as an escape character and would silently
# mangle a Windows path.
$androidFull = [System.IO.Path]::GetFullPath($androidDir)
$fullKeystorePath = [System.IO.Path]::GetFullPath($KeystorePath)
$androidPrefix = $androidFull.TrimEnd([System.IO.Path]::DirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
if ($fullKeystorePath.StartsWith($androidPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
    $storeValue = $fullKeystorePath.Substring($androidPrefix.Length)
} else {
    $storeValue = $fullKeystorePath
}
$storeValue = $storeValue -replace '\\', '/'

# A keystore inside the repo but outside the ignored paths would be committed on
# the next `git add -A`. Warn rather than fail, since the caller may have their
# own arrangement.
if ($fullKeystorePath.StartsWith($repoRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    & git -C $repoRoot check-ignore -q -- $fullKeystorePath 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "$fullKeystorePath is inside the repository but is NOT gitignored. Move it under webapp/android/app/ or add it to .gitignore before committing anything."
    }
}

@(
    '# Generated by scripts/New-ReleaseKeystore.ps1. Gitignored - never commit.',
    "storeFile=$storeValue",
    "storePassword=$password",
    "keyAlias=$Alias",
    "keyPassword=$password"
) | Set-Content -Path $PropertiesPath -Encoding ASCII

$fingerprint = (& $keytool -list -v -keystore $KeystorePath -storepass $password |
    Select-String -Pattern 'SHA256:' | Select-Object -First 1).ToString().Trim()

Write-Host ''
Write-Host 'Release keystore created.' -ForegroundColor Green
Write-Host "  keystore   : $KeystorePath"
Write-Host "  properties : $PropertiesPath"
Write-Host "  alias      : $Alias"
Write-Host "  $fingerprint"
Write-Host ''
Write-Host 'Back up the keystore and its password now. Losing them means every' -ForegroundColor Yellow
Write-Host 'phone running the app must uninstall before taking a future update.' -ForegroundColor Yellow
Write-Host ''
Write-Host 'To let CI sign releases, publish the same material as secrets:' -ForegroundColor Cyan
Write-Host '  cd webapp; npm run android:signing:secrets'
